### ISSUE TITLE
Will upgrade to get the wwdc 2015?

### ISSUE THREAD

**Issue by lucascorrea** [jfahrenkrug/WWDC-Downloader#26]
Will upgrade to get the wwdc 2015?

**Comment by jfahrenkrug** [comment]
Yes I will :)

**Comment by lucascorrea** [comment]
Thank you, see you updated.

**Comment by lucascorrea** [comment]
Error.

WWDC 2014 Session Material Downloader
by Johannes Fahrenkrug, @jfahrenkrug, springenwerk.com
See you next year!

Enter your ADC password:  ********
/usr/local/lib/ruby/gems/2.1.0/gems/wwdcdownloader-20.14.1/lib/wwdcdownloader.rb:83:in `block in login': undefined method `options' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.1.0/gems/mechanize-2.7.3/lib/mechanize.rb:442:in `get'
	from /usr/local/lib/ruby/gems/2.1.0/gems/wwdcdownloader-20.14.1/lib/wwdcdownloader.rb:66:in `login'
	from /usr/local/lib/ruby/gems/2.1.0/gems/wwdcdownloader-20.14.1/lib/wwdcdownloader.rb:271:in `run!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/wwdcdownloader-20.14.1/bin/wwdcdownloader:5:in `<top (required)>'
	from /usr/local/bin/wwdcdownloader:23:in `load'
	from /usr/local/bin/wwdcdownloader:23:in `<main>'

**Comment by jfahrenkrug** [comment]
Try to update again. You are running the 2014 version. Then it should work!
