### ISSUE TITLE
It doesn't skip already downloaded files for some reason

### ISSUE THREAD

**Issue by avioli** [jfahrenkrug/WWDC-Downloader#27]
It doesn't skip already downloaded files for some reason.

Invoking with:
```
wwdcdownloader wwdc/2015/Sample\ Code/
```

**Comment by jfahrenkrug** [comment]
@avioli You are right, that's currently not implemented. I'll take a look!

**Comment by jfahrenkrug** [comment]
Fixed in 20.15.1
