### ISSUE TITLE
WWDC 2014 Sample Code lost, no longer downloadable

### ISSUE THREAD

**Issue by kludgeless** [jfahrenkrug/WWDC-Downloader#29]
This is a fantastic tool. Just finished downloading all the 2015 samples and it worked brilliantly. Also found the 2013 samples here:

https://developer.apple.com/downloads/?name=WWDC%202013

The problem I've run into is I can't seem to find the WWDC 2014 sample code anywhere. Does anyone here know how to obtain it, or still have a copy?

I was specifically looking for the VisualEffectPlayground sample code from Session 220, but I'd also like to help get all the samples from WWDC 2014 downloadable again or hosted somewhere for others.

**Comment by jfahrenkrug** [comment]
Hi! Thank you :)
I couldn't really find it either. I found this Xamarin port of it: https://github.com/xamarin/mac-samples/tree/master/yosemite/VisualEffectPlayground 
Maybe that's helpful :-/

**Comment by kludgeless** [comment]
Thanks! I actually contacted the guy who ported that as well, but it seems no one has kept copies. Think I'll hit up an Apple evangelist next, see if they can find them :)

**Comment by jfahrenkrug** [comment]
Great, I hope they can help you. I unfortunately didn't keep the files that I downloaded with the WWDC-Downloader last year. That'll teach me :)
