### ISSUE TITLE
Extend to prior years

### ISSUE THREAD

**Issue by mingsai** [jfahrenkrug/WWDC-Downloader#30]
Is it possible to add parameter support so that we can pull projects from prior years? I note that often other years' data may be available on the developer website.

**Comment by mickeyl** [comment]
Good idea, I'd like to see that as well.

**Comment by lemonkey** [comment]
The old version did this.

**Comment by jfahrenkrug** [comment]
This is unfortunately not easy to do since Apple takes the previous year's WWDC schedule and linked resources offline when the new schedule is uploaded. It will most likely always only work for the current year.
