### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by klische** [jfahrenkrug/WWDC-Downloader#35]
EDIT: Happens when running the wwdcdownloader script

/var/lib/gems/1.9.1/gems/json-1.8.6/lib/json/common.rb:155:in `parse': 784: unexpected token at '' (JSON::ParserError)
	from /var/lib/gems/1.9.1/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
	from /var/lib/gems/1.9.1/gems/wwdcdownloader-20.17.0/lib/wwdcdownloader.rb:124:in `block in load'
	from /var/lib/gems/1.9.1/gems/wwdcdownloader-20.17.0/lib/wwdcdownloader.rb:72:in `block in read_url'
	from /usr/lib/ruby/1.9.1/net/http.rb:746:in `start'
	from /var/lib/gems/1.9.1/gems/wwdcdownloader-20.17.0/lib/wwdcdownloader.rb:67:in `read_url'
	from /var/lib/gems/1.9.1/gems/wwdcdownloader-20.17.0/lib/wwdcdownloader.rb:123:in `load'
	from /var/lib/gems/1.9.1/gems/wwdcdownloader-20.17.0/lib/wwdcdownloader.rb:243:in `run!'
	from /var/lib/gems/1.9.1/gems/wwdcdownloader-20.17.0/bin/wwdcdownloader:5:in `<top (required)>'
	from /usr/local/bin/wwdcdownloader:23:in `load'
	from /usr/local/bin/wwdcdownloader:23:in `<main>'

**Comment by jfahrenkrug** [comment]
@klische Thank you for the report. Is this still happening for you? I can't reproduce it.

**Comment by klische** [comment]
@jfahrenkrug Just tried it, and still happening :( Perhaps something wrong with my Ruby installation?

**Comment by klische** [comment]
Totally my fault. Updated to latest ruby by following directions here https://www.brightbox.com/blog/2017/04/25/updated-ruby-ubuntu-packages/

PS. For others with the same issue, make sure to apt-get install ruby2.4 and ruby2.4-dev and then reinstall the wwdcdownloader gem
